export type Exercise = {
  id: string;
  name: string;
  category: "push" | "pull" | "legs" | "core" | "cardio" | "mobility";
  primary: string[];
  secondary: string[];
  equipment: string[];
  cues: string[];
  defaultReps: string;
};

export const exercises: Record<string, Exercise> = {
  bench: {
    id: "bench",
    name: "Barbell Bench Press",
    category: "push",
    primary: ["Chest"],
    secondary: ["Triceps", "Front delts"],
    equipment: ["Barbell", "Bench"],
    cues: [
      "Plant feet flat, slight arch in lower back, shoulder blades retracted and tucked into bench.",
      "Grip just outside shoulder width; bar over mid-chest at lockout.",
      "Lower bar to lower-chest line with elbows ~45-60° from torso, touch lightly.",
      "Drive through chest and triceps; keep wrists straight and elbows tracking with the bar.",
    ],
    defaultReps: "6-10",
  },
  incline_db_press: {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    category: "push",
    primary: ["Upper chest"],
    secondary: ["Front delts", "Triceps"],
    equipment: ["Dumbbells", "Incline bench"],
    cues: [
      "Bench at 30°; sit with dumbbells on thighs, kick back as you lie down.",
      "Press with dumbbells slightly converging at the top.",
      "Lower to chest level, pause briefly, drive up.",
    ],
    defaultReps: "8-12",
  },
  ohp: {
    id: "ohp",
    name: "Overhead Press",
    category: "push",
    primary: ["Shoulders"],
    secondary: ["Triceps", "Upper chest"],
    equipment: ["Barbell"],
    cues: [
      "Bar in front rack, grip just outside shoulders, elbows slightly forward.",
      "Brace core, glutes tight; press straight up while pushing head through.",
      "Lock out overhead with bar stacked over mid-foot; lower with control.",
    ],
    defaultReps: "5-8",
  },
  dips: {
    id: "dips",
    name: "Parallel Bar Dips",
    category: "push",
    primary: ["Chest", "Triceps"],
    secondary: ["Front delts"],
    equipment: ["Dip bars"],
    cues: [
      "Lean slightly forward for chest emphasis, vertical for triceps.",
      "Lower until upper arms are parallel to floor; don't flare elbows wide.",
      "Press through palms; squeeze chest at top.",
    ],
    defaultReps: "8-12",
  },
  pushup: {
    id: "pushup",
    name: "Push-Up",
    category: "push",
    primary: ["Chest"],
    secondary: ["Triceps", "Front delts", "Core"],
    equipment: ["Bodyweight"],
    cues: [
      "Plank position, hands under shoulders, body in a straight line from heels to head.",
      "Lower chest to within fist's width of the floor.",
      "Push the floor away; don't let hips sag.",
    ],
    defaultReps: "10-20",
  },
  lateral_raise: {
    id: "lateral_raise",
    name: "Dumbbell Lateral Raise",
    category: "push",
    primary: ["Side delts"],
    secondary: [],
    equipment: ["Dumbbells"],
    cues: [
      "Slight forward lean, tiny knee bend, dumbbells in front of thighs.",
      "Raise with elbows leading slightly, pinkies up at the top.",
      "Stop at shoulder height; lower under control for 2-3 sec.",
    ],
    defaultReps: "12-15",
  },
  tricep_pushdown: {
    id: "tricep_pushdown",
    name: "Cable Triceps Pushdown",
    category: "push",
    primary: ["Triceps"],
    secondary: [],
    equipment: ["Cable"],
    cues: [
      "Elbows pinned to ribs the entire set.",
      "Press down by extending elbows only; lock out short of full hyperextension.",
      "Slight forward lean keeps tension on the long head.",
    ],
    defaultReps: "10-15",
  },
  skullcrusher: {
    id: "skullcrusher",
    name: "Lying Triceps Extension (Skullcrusher)",
    category: "push",
    primary: ["Triceps"],
    secondary: [],
    equipment: ["EZ bar", "Bench"],
    cues: [
      "Bar starts over forehead with arms slightly past vertical (loads long head).",
      "Lower to just behind forehead by bending elbows only.",
      "Extend back without flaring elbows.",
    ],
    defaultReps: "8-12",
  },

  pullup: {
    id: "pullup",
    name: "Pull-Up",
    category: "pull",
    primary: ["Lats"],
    secondary: ["Biceps", "Mid back"],
    equipment: ["Pull-up bar"],
    cues: [
      "Hang with shoulders pulled away from ears.",
      "Drive elbows down and back; chest to bar if possible.",
      "Control descent; don't dead-hang between reps in a working set.",
    ],
    defaultReps: "5-10",
  },
  lat_pulldown: {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    category: "pull",
    primary: ["Lats"],
    secondary: ["Biceps", "Mid back"],
    equipment: ["Cable"],
    cues: [
      "Grip just wider than shoulders; lean back ~15°.",
      "Pull bar to upper chest by driving elbows toward your back pockets.",
      "Slow eccentric, fully stretch at top without losing scapular position.",
    ],
    defaultReps: "10-12",
  },
  barbell_row: {
    id: "barbell_row",
    name: "Barbell Row",
    category: "pull",
    primary: ["Mid back", "Lats"],
    secondary: ["Rear delts", "Biceps"],
    equipment: ["Barbell"],
    cues: [
      "Hinge to ~45°, neutral spine, bar over mid-foot.",
      "Row to lower chest/upper abs by pulling elbows back.",
      "Squeeze scapulae for a beat at top; don't yank with hips.",
    ],
    defaultReps: "6-10",
  },
  db_row: {
    id: "db_row",
    name: "One-Arm Dumbbell Row",
    category: "pull",
    primary: ["Lats", "Mid back"],
    secondary: ["Biceps"],
    equipment: ["Dumbbell", "Bench"],
    cues: [
      "One knee + same-side hand on bench; back flat.",
      "Pull dumbbell to hip with elbow tracking back, not flaring out.",
      "Lower with control, full stretch at the bottom.",
    ],
    defaultReps: "8-12",
  },
  face_pull: {
    id: "face_pull",
    name: "Cable Face Pull",
    category: "pull",
    primary: ["Rear delts"],
    secondary: ["Mid traps", "Rotator cuff"],
    equipment: ["Cable", "Rope"],
    cues: [
      "Rope at head height; step back to get tension.",
      "Pull rope toward eyes, hands going past ears, elbows high.",
      "Externally rotate at end; pause and squeeze.",
    ],
    defaultReps: "12-15",
  },
  bb_curl: {
    id: "bb_curl",
    name: "Barbell Curl",
    category: "pull",
    primary: ["Biceps"],
    secondary: ["Forearms"],
    equipment: ["Barbell"],
    cues: [
      "Elbows pinned at sides, slight forward lean kills body english.",
      "Curl to ~90% range; don't bring bar all the way up where tension drops.",
      "Lower under control; don't let elbows drift forward.",
    ],
    defaultReps: "8-12",
  },
  hammer_curl: {
    id: "hammer_curl",
    name: "Hammer Curl",
    category: "pull",
    primary: ["Biceps (brachialis)"],
    secondary: ["Forearms"],
    equipment: ["Dumbbells"],
    cues: [
      "Neutral grip throughout.",
      "Alternate or both at once; slight pause at top.",
    ],
    defaultReps: "10-12",
  },

  back_squat: {
    id: "back_squat",
    name: "Barbell Back Squat",
    category: "legs",
    primary: ["Quads", "Glutes"],
    secondary: ["Hamstrings", "Core"],
    equipment: ["Barbell", "Rack"],
    cues: [
      "Bar high or low; brace core hard before unrack.",
      "Stance shoulder-width, toes slightly out; track knees over toes.",
      "Sit between hips; depth at least parallel; drive through whole foot.",
    ],
    defaultReps: "5-8",
  },
  front_squat: {
    id: "front_squat",
    name: "Front Squat",
    category: "legs",
    primary: ["Quads"],
    secondary: ["Upper back", "Core"],
    equipment: ["Barbell", "Rack"],
    cues: [
      "Bar across front delts in clean grip or cross-arm.",
      "Keep elbows up the entire rep; loss of elbows = bar dump.",
      "Sit straight down; torso stays very upright.",
    ],
    defaultReps: "5-8",
  },
  leg_press: {
    id: "leg_press",
    name: "Leg Press",
    category: "legs",
    primary: ["Quads", "Glutes"],
    secondary: ["Hamstrings"],
    equipment: ["Leg press machine"],
    cues: [
      "Feet shoulder-width on middle of platform.",
      "Lower under control; stop when lower back starts to round.",
      "Drive through whole foot; don't lock knees hard at top.",
    ],
    defaultReps: "8-12",
  },
  rdl: {
    id: "rdl",
    name: "Romanian Deadlift",
    category: "legs",
    primary: ["Hamstrings", "Glutes"],
    secondary: ["Lower back"],
    equipment: ["Barbell"],
    cues: [
      "Soft knees, then hinge from hips by pushing hips back.",
      "Bar stays close to legs; descent is hips, not knees.",
      "Go until you feel a strong hamstring stretch; drive hips forward to stand.",
    ],
    defaultReps: "8-10",
  },
  deadlift: {
    id: "deadlift",
    name: "Conventional Deadlift",
    category: "legs",
    primary: ["Hamstrings", "Glutes", "Lower back"],
    secondary: ["Lats", "Traps", "Core"],
    equipment: ["Barbell"],
    cues: [
      "Bar over mid-foot; grip just outside knees.",
      "Brace before lifting; pull slack out of the bar.",
      "Push the floor away; bar drags up legs; lockout glutes hard without overextending.",
    ],
    defaultReps: "3-5",
  },
  hip_thrust: {
    id: "hip_thrust",
    name: "Barbell Hip Thrust",
    category: "legs",
    primary: ["Glutes"],
    secondary: ["Hamstrings"],
    equipment: ["Barbell", "Bench"],
    cues: [
      "Shoulder blades on bench, knees ~90° at top.",
      "Drive heels into floor; squeeze glutes at the top for a beat.",
      "Avoid hyperextending lumbar — ribs down.",
    ],
    defaultReps: "8-12",
  },
  walking_lunge: {
    id: "walking_lunge",
    name: "Walking Lunge",
    category: "legs",
    primary: ["Quads", "Glutes"],
    secondary: ["Hamstrings", "Core"],
    equipment: ["Dumbbells"],
    cues: [
      "Long step forward; back knee almost kisses the floor.",
      "Drive off front heel into next step.",
      "Torso upright; control your tempo, don't bounce.",
    ],
    defaultReps: "10/leg",
  },
  leg_curl: {
    id: "leg_curl",
    name: "Lying / Seated Leg Curl",
    category: "legs",
    primary: ["Hamstrings"],
    secondary: [],
    equipment: ["Machine"],
    cues: [
      "Knee axis aligned with machine pivot.",
      "Curl with full range; 1-second squeeze at the top.",
      "Lower over 2-3 sec.",
    ],
    defaultReps: "10-15",
  },
  leg_extension: {
    id: "leg_extension",
    name: "Leg Extension",
    category: "legs",
    primary: ["Quads"],
    secondary: [],
    equipment: ["Machine"],
    cues: [
      "Pad just above ankle, knees aligned with pivot.",
      "Squeeze quads at lockout for a second.",
      "Slight forward lean increases rectus femoris activation.",
    ],
    defaultReps: "12-15",
  },
  calf_raise: {
    id: "calf_raise",
    name: "Standing Calf Raise",
    category: "legs",
    primary: ["Calves"],
    secondary: [],
    equipment: ["Machine"],
    cues: [
      "Full stretch at the bottom; pause 1 sec.",
      "Drive up onto big toe; pause at the top.",
      "Slow eccentric is where most growth happens.",
    ],
    defaultReps: "12-20",
  },

  plank: {
    id: "plank",
    name: "Front Plank",
    category: "core",
    primary: ["Core"],
    secondary: ["Glutes"],
    equipment: ["Bodyweight"],
    cues: [
      "Forearms shoulder-width, elbows under shoulders.",
      "Squeeze glutes and abs; ribs down.",
      "Don't let hips sag or pike up.",
    ],
    defaultReps: "30-60s",
  },
  hanging_leg_raise: {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    category: "core",
    primary: ["Lower abs", "Hip flexors"],
    secondary: ["Grip", "Lats"],
    equipment: ["Pull-up bar"],
    cues: [
      "Hollow body; don't swing.",
      "Tuck pelvis as legs rise to bring abs into play.",
      "Lower with control over 2-3 sec.",
    ],
    defaultReps: "8-12",
  },
  cable_crunch: {
    id: "cable_crunch",
    name: "Cable Crunch",
    category: "core",
    primary: ["Abs"],
    secondary: [],
    equipment: ["Cable", "Rope"],
    cues: [
      "Kneel below cable; rope at sides of head.",
      "Curl your spine, bringing elbows toward thighs — not hip flexion.",
      "Slow return; keep tension throughout.",
    ],
    defaultReps: "12-15",
  },

  treadmill_zone2: {
    id: "treadmill_zone2",
    name: "Zone 2 Treadmill",
    category: "cardio",
    primary: ["Heart", "Lungs"],
    secondary: ["Legs"],
    equipment: ["Treadmill"],
    cues: [
      "Pace where you can speak in full sentences but not sing.",
      "Heart rate ~60-70% of max (roughly 130-145 bpm for most adults).",
      "Aim for 30-45 minutes continuous.",
    ],
    defaultReps: "30-45 min",
  },
  rower: {
    id: "rower",
    name: "Rowing Machine",
    category: "cardio",
    primary: ["Heart", "Lungs"],
    secondary: ["Lats", "Mid back", "Quads", "Glutes"],
    equipment: ["Erg"],
    cues: [
      "Drive sequence: legs, hips, then arms.",
      "Recovery sequence: arms, hips, then legs.",
      "Stroke rate around 20-26 spm for endurance.",
    ],
    defaultReps: "15-30 min",
  },
  bike_intervals: {
    id: "bike_intervals",
    name: "Bike HIIT Intervals",
    category: "cardio",
    primary: ["Heart", "Lungs"],
    secondary: ["Quads", "Glutes"],
    equipment: ["Bike"],
    cues: [
      "Warm up 5 min easy.",
      "Repeat: 30 seconds all-out, 90 seconds easy spinning.",
      "8-10 rounds; cool down 5 min.",
    ],
    defaultReps: "8x 30/90",
  },
};

export const exerciseList = Object.values(exercises);
export const exerciseIds = Object.keys(exercises);
